//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "tasks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i64,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub program: String,
    #[sea_orm(column_type = "Text")]
    pub args: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub stdin: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stdout: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub stderr: Option<String>,
    pub enabled: bool,
    #[sea_orm(column_type = "Text")]
    pub trigger_tag: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub trigger_content: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
